"use client";

import React, { useEffect, useState } from "react";
import { FileText, Shield, Activity, Download } from "lucide-react";

const Report = () => {
  const [report, setReport] = useState(null);

  useEffect(() => {
    fetch("http://localhost:5000/api/report")
      .then((res) => {
        if (!res.ok) {
          throw new Error("Network response was not ok");
        }
        return res.json();
      })
      .then((data) => setReport(data))
      .catch((err) => {
        console.error("Error fetching report, using fallback data:", err);
        setReport({
          symptoms: ["Fever", "Headache", "Fatigue"], // ✅ No stringify needed for fallback object structure
          advice: ["Stay hydrated", "Rest for at least 2 days", "Take paracetamol for fever"],
          precautions: ["Wear a mask", "Isolate from family members", "Monitor temperature"],
          ai_summary: "Based on the symptoms provided, it appears to be a viral fever. Please consult a doctor if symptoms persist.",
          created_at: new Date().toISOString()
        });
      });
  }, []);

  if (!report) {
    return <div className="text-center mt-20">Loading Report...</div>;
  }

  // ✅ Backend now sends arrays directly. No parsing needed!
  const symptoms = report.symptoms || [];
  const advice = report.advice || [];
  const precautions = report.precautions || [];

  return (
    <div className="max-w-4xl mx-auto p-6">
      <div className="bg-white shadow-xl rounded-2xl overflow-hidden">

        {/* Header */}
        <div className="bg-blue-600 p-6 text-white flex justify-between">
          <div>
            <h2 className="text-2xl font-bold">Health Assessment Report</h2>
            <p className="text-sm opacity-80">
              Generated by AI • {new Date(report.created_at).toLocaleDateString()}
            </p>
          </div>
          <FileText size={40} className="opacity-40" />
        </div>

        <div className="p-8 space-y-8">

          {/* Symptoms */}
          <section>
            <h3 className="text-gray-500 uppercase text-sm mb-3">
              Symptoms Reported
            </h3>
            <div className="flex flex-wrap gap-2">
              {symptoms.map((s, i) => (
                <span key={i} className="bg-red-50 text-red-700 px-3 py-1 rounded-full">
                  {s}
                </span>
              ))}
            </div>
          </section>

          {/* AI Summary */}
          <section className="border-l-4 border-blue-500 bg-blue-50 p-4 rounded">
            <h3 className="font-semibold text-blue-800 mb-2">AI Summary</h3>
            <p>{report.ai_summary}</p>
          </section>

          {/* Advice & Precautions */}
          <div className="grid md:grid-cols-2 gap-8">
            <section>
              <h3 className="flex items-center font-bold mb-2">
                <Shield className="mr-2 text-green-600" /> Advice
              </h3>
              <ul className="list-disc ml-5">
                {advice.map((a, i) => <li key={i}>{a}</li>)}
              </ul>
            </section>

            <section>
              <h3 className="flex items-center font-bold mb-2">
                <Activity className="mr-2 text-red-600" /> Precautions
              </h3>
              <ul className="list-disc ml-5">
                {precautions.map((p, i) => <li key={i}>{p}</li>)}
              </ul>
            </section>
          </div>

          {/* Buttons */}
          <div className="flex gap-4 pt-6 border-t">
            <button className="flex-1 bg-blue-600 text-white py-3 rounded-lg flex justify-center gap-2">
              <Download size={18} /> Download PDF
            </button>
            <button className="flex-1 border py-3 rounded-lg">
              View History
            </button>
          </div>

        </div>
      </div>
    </div>
  );
};

export default Report;
